Hel 238/récupérer les données errd pour le bloc budget et finances
DNUM-SocialGouv/helios pull request #156
Opened 2022-09-20 13:40 UTC by goth-octo

2022-09-20 16:06 UTC, sofcalca requested changes

2022-09-20 16:06 UTC, sofcalca commented on datacrawler/load/nom_des_tables.py
> +    DIAMANT_ANN_ERRD_EJ_ET_BUDGET_ET_FINANCES = "ann_errd_ej_et_budget_et_finances"
en fait on a discuté avec @NerOcrO et on va gérer les dates plus tard - quand on passera sur l'autom de DIAMANT. Par conséquence, on peut défaire ça et utiliser "DIAMANT_ANN_ERRD_EJ_ET". Dispo pour en parler si tu veux.

2022-09-21 11:51 UTC, NerOcrO commented on datacrawler/transform/transforme_le_bloc_budget_et_finances_des_établissements_médico_sociaux/transforme_le_bloc_budget_et_finances_des_établissements_médico_sociaux.py
> +def convertis_la_contribution_frais_de_siège_groupement_en_valuer_positive(ligne: pd.Series) -> pd.Series:
```suggestion
def convertis_la_contribution_frais_de_siège_groupement_en_valeur_positive(ligne: pd.Series) -> pd.Series:
```

2022-09-21 11:51 UTC, NerOcrO commented on datacrawler/transform/transforme_le_bloc_budget_et_finances_des_établissements_médico_sociaux/transforme_le_bloc_budget_et_finances_des_établissements_médico_sociaux_test.py
> +    def test_renomme_les_colonnes_et_crée_l_index(self) -> None:
Spécifier dans le test que `contribution_frais_de_siege_groupement` doit être positif ou alors écrire un second test juste pour ça.

2022-09-21 16:05 UTC, sofcalca approved these changes

2022-09-21 16:06 UTC, merged